"""Initial Supabase schema

Revision ID: 611f37e3e0e7
Revises: 
Create Date: 2026-09-24 15:37:32.205263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611f37e3e0e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kaggle_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('kernel_id', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kernel_id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('username')
    )
    op.create_table('platform_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('account_label', sa.String(length=200), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'account_label')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('niche', sa.String(length=255), nullable=False),
    sa.Column('style_notes', sa.Text(), nullable=True),
    sa.Column('creative_brief', sa.JSON(), nullable=False),
    sa.Column('kaggle_account_id', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('target_platforms', sa.JSON(), nullable=False),
    sa.Column('resolution_preset', sa.String(length=80), nullable=False),
    sa.Column('custom_width', sa.Integer(), nullable=True),
    sa.Column('custom_height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('chunk_seconds', sa.Integer(), nullable=False),
    sa.Column('use_turbo_lora', sa.Boolean(), nullable=False),
    sa.Column('turbo_steps', sa.Integer(), nullable=False),
    sa.Column('video_crf', sa.Integer(), nullable=False),
    sa.Column('video_preset', sa.String(length=16), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_job_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['kaggle_account_id'], ['kaggle_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('kaggle_account_id', sa.Integer(), nullable=True),
    sa.Column('kaggle_account_name', sa.String(length=120), nullable=True),
    sa.Column('niche', sa.String(length=255), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('generation_params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('kaggle_kernel_version', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('log_tail', sa.Text(), nullable=True),
    sa.Column('manifest_json', sa.JSON(), nullable=True),
    sa.Column('video_storage_path', sa.String(length=512), nullable=True),
    sa.Column('target_platforms', sa.JSON(), nullable=False),
    sa.Column('post_results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kaggle_account_id'], ['kaggle_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_generation_jobs_video_storage_path'), 'generation_jobs', ['video_storage_path'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_jobs')
    op.drop_table('schedules')
    op.drop_table('platform_credentials')
    op.drop_table('kaggle_accounts')
    # ### end Alembic commands ###
